services:
  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    env_file:
      - ./backend/auth-service/.env
    restart: unless-stopped

  gallery-service:
    build: ./backend/gallery-service
    container_name: gallery-service
    ports:
      - "3001:3001"
    env_file:
      - ./backend/gallery-service/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - gallery-service
    restart: unless-stopped
