apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fullstack-cloudit
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: auth-service
          image: ghcr.io/1durch0/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fullstack-cloudit
spec:
  selector:
    app: auth-service
  ports:
    - port: 3000
      targetPort: 3000
